/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package frpwrapper */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
extern size_t _GoStringLen(_GoString_ s);
extern const char *_GoStringPtr(_GoString_ s);
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 3 "frpwrapper.go"



#include <jni.h>
#include <stdlib.h>
#include <android/log.h>

#define LOG_TAG "FRP_NATIVE"
#define LOGI(...) __android_log_print(ANDROID_LOG_INFO, LOG_TAG, __VA_ARGS__)
#define LOGE(...) __android_log_print(ANDROID_LOG_ERROR, LOG_TAG, __VA_ARGS__)

static const char* GetStringUTFChars(JNIEnv* env, jstring str, jboolean* isCopy) {
    if (str == NULL) return NULL;
    return (*env)->GetStringUTFChars(env, str, isCopy);
}

static void ReleaseStringUTFChars(JNIEnv* env, jstring str, const char* chars) {
    if (env == NULL || str == NULL || chars == NULL) return;
    (*env)->ReleaseStringUTFChars(env, str, chars);
}

static void log_info(const char* msg) { LOGI("%s", msg); }
static void log_error(const char* msg) { LOGE("%s", msg); }

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#if !defined(__cplusplus) || _MSVC_LANG <= 201402L
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
#include <complex>
typedef std::complex<float> GoComplex64;
typedef std::complex<double> GoComplex128;
#endif
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif

extern void Java_frpwrapper_Frpwrapper_init(JNIEnv* env, jclass clazz, jstring cacheDir);
extern void Java_frpwrapper_Frpwrapper_startFrps(JNIEnv* env, jclass clazz, jstring config);
extern void Java_frpwrapper_Frpwrapper_stopFrps(JNIEnv* env, jclass clazz);
extern void Java_frpwrapper_Frpwrapper_startFrpc(JNIEnv* env, jclass clazz, jstring config);
extern void Java_frpwrapper_Frpwrapper_stopFrpc(JNIEnv* env, jclass clazz);
extern jboolean Java_frpwrapper_Frpwrapper_isFrpsRunning(JNIEnv* env, jclass clazz);
extern jboolean Java_frpwrapper_Frpwrapper_isFrpcRunning(JNIEnv* env, jclass clazz);
extern jboolean Java_frpwrapper_Frpwrapper_checkPort(JNIEnv* env, jclass clazz, jint port);

#ifdef __cplusplus
}
#endif
