// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBF7zGxl3pkqUzntAMwU00fY3qRX8LzFHY',
    appId: '1:467512100442:web:72d0d6917e40fe773a3a63',
    messagingSenderId: '467512100442',
    projectId: 'orbitx-os',
    authDomain: 'orbitx-os.firebaseapp.com',
    databaseURL: 'https://orbitx-os-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'orbitx-os.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfK_IX4uLX4rpVjzKr5apyiOFkOXO5_Rw',
    appId: '1:467512100442:android:916a577312390c983a3a63',
    messagingSenderId: '467512100442',
    projectId: 'orbitx-os',
    databaseURL: 'https://orbitx-os-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'orbitx-os.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPMfxsZEBDiDBQPwK6lnjIm3mZBj02l_8',
    appId: '1:467512100442:ios:f1bb95d472fb3f5e3a3a63',
    messagingSenderId: '467512100442',
    projectId: 'orbitx-os',
    databaseURL: 'https://orbitx-os-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'orbitx-os.firebasestorage.app',
    iosBundleId: 'com.shiva2232.orbitx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPMfxsZEBDiDBQPwK6lnjIm3mZBj02l_8',
    appId: '1:467512100442:ios:f1bb95d472fb3f5e3a3a63',
    messagingSenderId: '467512100442',
    projectId: 'orbitx-os',
    databaseURL: 'https://orbitx-os-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'orbitx-os.firebasestorage.app',
    iosBundleId: 'com.shiva2232.orbitx',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBF7zGxl3pkqUzntAMwU00fY3qRX8LzFHY',
    appId: '1:467512100442:web:91a9278c52d3e7c73a3a63',
    messagingSenderId: '467512100442',
    projectId: 'orbitx-os',
    authDomain: 'orbitx-os.firebaseapp.com',
    databaseURL: 'https://orbitx-os-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'orbitx-os.firebasestorage.app',
  );

}